### ISSUE TITLE
Bug: Keys are duplicated when data is imported using 'meltano elt SOURCE target-duckdb'

### ISSUE THREAD

**Issue by matsonj** [jwills/target-duckdb#11]
**Describe the bug**
When you execute 'meltano elt SOURCE target-duckdb', instead of only detecting incremental changes. It appears this is because "_smart_source_lineno" is getting populated with null.

**To Reproduce**
1. config any csv with tap-spreadsheets-anywhere.
2. run elt with target-duckdb
3. run it again
4. the data will be added the table again.

**Expected behavior**
only new records are added on step 3 when you run elt again. also, the column list should not change (meltano is running ALTER table to modify column names even when the source is unchanged in order to handle 'duplicate columns' for _smart_source_lineno".

**Screenshots**
![image](https://user-images.githubusercontent.com/16811433/193464701-2d649a17-980c-4189-a59d-47fc64c95f39.png)

**Your environment**
 - Version of target: latest
 - Version of python 3.10.4

**Comment by matsonj** [comment]
example tap config:
```
plugins:
  extractors:
  - name: tap-spreadsheets-anywhere
    variant: ets
    pip_url: git+https://github.com/ets/tap-spreadsheets-anywhere.git
    config:
      tables:
      - path: file:///path/to/file
        name: test_load
        pattern: .*
        start_date: '2001-01-01T00:00:00Z'
        key_properties: [key]
```
[test_load.csv](https://github.com/jwills/target-duckdb/files/9692979/test_load.csv)

After running 'meltano elt tap-spreadsheets-anywhere target-duckdb' it will have 8 rows (should have 4). In my experience with identical config, this same behavior does not replicate with the postgres target. But I have not tried this explicitly.
