### ISSUE TITLE
Cannot start plugin target-duckdb: Executable 'target-duckdb' could not be found. 

### ISSUE THREAD

**Issue by landajaromir** [jwills/target-duckdb#49]
Hello, I tries using your loader in my meltano project, however when I try to run it I get this error:
Cannot start plugin target-duckdb: Executable 'target-duckdb' could not be found. Loader 'target-duckdb' may not have been installed yet using `meltano install loader target-duckdb`, or the executable name may be incorrect.

My meltano.yml looks like this:
```
version: 1
send_anonymous_usage_stats: false
project_id: taposm
default_environment: dev
environments:
- name: dev
plugins:
  extractors:
  - name: taposm
    namespace: taposm
    pip_url: -e .
  loaders:
  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.6
    config:
      dbname: taposm
```
and when i run `meltano install`, everything installs. 

However, when I try to run my tools using `meltano run taposm target-duckdb`, I get the error.
